[window]
opacity = 0.92
decorations = "None"
dynamic_title = true

[window.padding]
x = 16
y = 14

[font]
size = 10.0

[font.normal]
family = "Inconsolata Nerd Font Mono"
style = "Regular"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Beam"
blinking = "On"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.primary]
background = "#2e3440"
foreground = "#eceff4"
dim_foreground = "#d8dee9"
bright_foreground = "#ffffff"

[colors.cursor]
text = "#2e3440"
cursor = "#eceff4"

[colors.selection]
text = "#eceff4"
background = "#4c566a"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"